import { useEffect, useRef, useState } from "react";
import { getCurrentCoordinates } from "../application/waypointService";
import { appendPoint, finishRecording, loadRecording, pauseRecording, persistRecording, recordedDistanceMeters, recordingElapsedMs, resumeRecording, samplingIntervals, startRecording, type SamplingPreset, type TrackRecording } from "../application/trackRecordingService";

export function AutomaticTrackRecordingDialog({ tripId, onClose }: { tripId: string; onClose: () => void }) {
  const [recording, setRecording] = useState<TrackRecording>();
  const [message, setMessage] = useState("");
  const recordingRef = useRef<TrackRecording | undefined>(undefined);
  const persist = async (next: TrackRecording) => { recordingRef.current = next; setRecording(next); await persistRecording(tripId, next); };
  const capture = async (current: TrackRecording) => { try { await persist(appendPoint(current, await getCurrentCoordinates())); } catch (error) { setMessage(error instanceof Error ? error.message : "Location is unavailable."); } };
  useEffect(() => { recordingRef.current = recording; }, [recording]);
  useEffect(() => { let live = true; void loadRecording(tripId).then((saved) => { if (live) { recordingRef.current = saved; setRecording(saved); } }); return () => { live = false; }; }, [tripId]);
  const isRecording = recording?.state === "recording";
  const samplingPreset = recording?.preset;
  useEffect(() => { if (!isRecording || !samplingPreset) return; const timer = window.setInterval(() => { const active = recordingRef.current; if (!active || active.state !== "recording") return; void getCurrentCoordinates().then(async (point) => { const next = appendPoint(active, point); recordingRef.current = next; setRecording(next); await persistRecording(tripId, next); }).catch(() => setMessage("Location is unavailable.")); }, samplingIntervals[samplingPreset]); return () => window.clearInterval(timer); }, [isRecording, samplingPreset, tripId]);
  async function start(preset: SamplingPreset) { const next = startRecording(preset); await persist(next); void capture(next); }
  async function stop() { if (!recording) return; const track = await finishRecording(tripId, recording); setRecording(undefined); setMessage(track ? `Saved ${track.points.length} points locally.` : "Need at least two points to save a track."); }
  return <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true" aria-label="Track recording"><div className="dialog-heading"><h2>Track recording</h2><button className="text-button" aria-label="Close dialog" type="button" onClick={onClose}>×</button></div><p className="empty-state">Tracking never begins automatically. After you start it, points are sampled at your selected interval and persisted locally.</p>{!recording && <div className="data-actions"><button className="primary-action" type="button" onClick={() => void start("balanced")}>Start balanced</button><button className="secondary-action" type="button" onClick={() => void start("battery-saver")}>Start battery saver</button></div>}{recording && <><p className="empty-state">{recording.state} · {recording.points.length} points · {(recordedDistanceMeters(recording.points) / 1000).toFixed(1)} km · {Math.floor(recordingElapsedMs(recording) / 60_000)} min · {samplingIntervals[recording.preset] / 1000}s target</p><div className="data-actions">{recording.state === "recording" && <><button className="primary-action" type="button" onClick={() => void capture(recording)}>Capture current point</button><button className="secondary-action" type="button" onClick={() => void persist(pauseRecording(recording))}>Pause</button></>}{recording.state === "paused" && <button className="primary-action" type="button" onClick={() => void persist(resumeRecording(recording))}>Resume</button>}<button className="secondary-action" type="button" onClick={() => void stop()}>Stop & save</button></div></>}{message && <p className="error-message" role="status">{message}</p>}</section></div>;
}
