import { useEffect, useState } from "react";
import { readContextLayers, refreshContextLayers, type ContextLayer } from "../application/contextLayerService";

export function ContextLayersDialog({ coordinates, onClose }: { coordinates?: { latitude: number; longitude: number }; onClose: () => void }) {
  const [layers, setLayers] = useState<ContextLayer[]>([]); const [enabled, setEnabled] = useState<Record<string, boolean>>({}); const [message, setMessage] = useState("");
  useEffect(() => { let active = true; if (coordinates) void readContextLayers(coordinates).then((cached) => { if (active && cached) { setLayers(cached); setEnabled(Object.fromEntries(cached.map((layer) => [layer.id, true]))); } }); return () => { active = false; }; }, [coordinates]);
  async function refresh() { if (!coordinates) return; try { const result = await refreshContextLayers(coordinates); setLayers(result.layers); setEnabled(Object.fromEntries(result.layers.map((layer) => [layer.id, true]))); setMessage(result.failed.length ? `Unavailable: ${result.failed.join(", ")}. Cached or missing layers are explicit.` : "Layers refreshed."); } catch { setMessage("Layers are unavailable. Base map and trip data still work."); } }
  return <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true" aria-label="Safety and access layers"><div className="dialog-heading"><h2>Safety & access layers</h2><button className="text-button" aria-label="Close dialog" type="button" onClick={onClose}>×</button></div><p className="empty-state">Legally designated/open is not physically reported passable. Missing data is unknown, never safe.</p>{coordinates ? <button className="primary-action" type="button" onClick={() => void refresh()}>Refresh layers</button> : <p className="empty-state">Add destination or site coordinates to load local area context.</p>}{message && <p className="error-message" role="status">{message}</p>}{layers.map((layer) => <section className="category-guide" key={layer.id}><label><input type="checkbox" checked={enabled[layer.id] ?? true} onChange={() => setEnabled((current) => ({ ...current, [layer.id]: !(current[layer.id] ?? true) }))} /> {layer.title}</label><p>{layer.legend}</p><small>Source: <a href={layer.sourceUrl} target="_blank" rel="noreferrer">open source</a> · fetched {new Date(layer.fetchedAt).toLocaleString()}</small>{enabled[layer.id] && <p>{layer.features.length} source features loaded.</p>}</section>)}</section></div>;
}
