import { ChangeEvent, useCallback, useEffect, useState } from "react";
import { createBackup, downloadText, parseBackup, restoreBackup } from "../application/backupService";
import { disableCloudBackup, enableInventoryCloudBackup, getCloudBackupStatus, syncInventoryCloudBackup, type CloudBackupStatus } from "../application/cloudBackupService";
import type { CloudAccount } from "../application/authService";

export function DataTools({ onBack, onRestored, cloudAccount }: { onBack: () => void; onRestored: () => void; cloudAccount?: CloudAccount | undefined }) {
  const [message, setMessage] = useState("");
  const [cloudStatus, setCloudStatus] = useState<CloudBackupStatus>();
  const [cloudBusy, setCloudBusy] = useState(false);
  const accountId = cloudAccount?.id;
  const refreshCloud = useCallback(async () => {
    const status = accountId ? await getCloudBackupStatus(accountId) : undefined;
    setCloudStatus(status);
  }, [accountId]);
  useEffect(() => {
    let active = true;
    if (accountId) void getCloudBackupStatus(accountId).then((status) => { if (active) setCloudStatus(status); });
    else void Promise.resolve().then(() => { if (active) setCloudStatus(undefined); });
    return () => { active = false; };
  }, [accountId]);
  async function exportBackup() { const backup = await createBackup(); downloadText(`camping-checklist-backup-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify(backup, null, 2), "application/json"); setMessage("Backup downloaded."); }
  async function importBackup(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; try { const backup = parseBackup(await file.text()); if (!window.confirm(`Replace all local checklist data with the ${backup.exportedAt.slice(0, 10)} backup? This cannot be undone.`)) return; await restoreBackup(backup); setMessage("Backup restored. Returning to your trips…"); onRestored(); } catch (error) { setMessage(error instanceof Error ? error.message : "Couldn’t restore that backup."); } finally { event.target.value = ""; } }
  async function runCloud(task: () => Promise<{ pulled: number; pushed: number; conflicts: number; error?: string }>) { setCloudBusy(true); try { const result = await task(); setMessage(result.error ?? `Cloud backup complete: ${result.pulled} downloaded, ${result.pushed} uploaded${result.conflicts ? `, ${result.conflicts} conflict${result.conflicts === 1 ? "" : "s"} retained locally` : ""}.`); await refreshCloud(); } catch (error) { setMessage(error instanceof Error ? error.message : "Cloud backup could not run."); } finally { setCloudBusy(false); } }
  return <main className="app-shell"><header className="trip-header"><button className="text-button" type="button" onClick={onBack}>← All trips</button><p className="eyebrow">LOCAL DATA</p><h1>Keep your lists safe.</h1></header><section className="inventory-card"><h2>Cloud & backup</h2>{cloudAccount ? <><p className="empty-state">Signed in as {cloudAccount.email}. Cloud backup is optional. Today it backs up only your master inventory; trips, locations, notes, maps, and safety details remain on this device.</p>{cloudStatus?.accountMatches === false ? <p className="error-message">This device's cloud backup is linked to another account. Local data has not been moved.</p> : <><p className="empty-state">{cloudStatus?.enabled ? `${cloudStatus.pendingChanges} change${cloudStatus.pendingChanges === 1 ? "" : "s"} pending${cloudStatus.lastSuccessfulSync ? ` · last synced ${new Date(cloudStatus.lastSuccessfulSync).toLocaleString()}` : ""}` : "Cloud backup is off."}</p><div className="data-actions"><button className="primary-action" type="button" disabled={cloudBusy} onClick={() => void runCloud(() => cloudStatus?.enabled ? syncInventoryCloudBackup(cloudAccount.id) : enableInventoryCloudBackup(cloudAccount.id))}>{cloudBusy ? "Syncing…" : cloudStatus?.enabled ? "Sync now" : "Enable inventory backup"}</button>{cloudStatus?.enabled && <button className="secondary-action" type="button" disabled={cloudBusy} onClick={() => void disableCloudBackup(cloudAccount.id).then(refreshCloud)}>Disable cloud backup</button>}</div>{cloudStatus?.lastError && <p className="error-message">Last cloud error: {cloudStatus.lastError}</p>}</>}</> : <p className="empty-state">Cloud backup is optional. Sign in from People & profiles to enable it; the app remains fully usable offline.</p>}</section><section className="inventory-card"><h2>Backup & restore</h2><p className="empty-state">Download a portable JSON backup of your lists, trips, meal plans, groceries, saved meals, profiles, sites, waypoints, weather, and routes. Downloaded map archives and prepared offline packs stay on this device.</p><div className="data-actions"><button className="primary-action" type="button" onClick={() => void exportBackup()}>Download backup</button><label className="secondary-action">Restore backup<input type="file" accept="application/json,.json" onChange={(event) => void importBackup(event)} /></label></div>{message && <p className="error-message" role="status">{message}</p>}</section></main>;
}
