import { FormEvent, useEffect, useMemo, useState } from "react";
import { archiveMasterItem, findMasterItems, listMasterItems, saveMasterItem } from "../application/inventoryService";
import type { ChecklistCategory, MasterItem, QuantityRule } from "../domain/models";

const categories: Record<ChecklistCategory, string> = { food: "Food", gear: "Gear", clothes: "Clothes", "hygiene-first-aid": "Hygiene & First Aid", extras: "Extras" };
const createId = () => `user-${crypto.randomUUID()}`;

export function InventoryScreen({ onBack }: { onBack: () => void }) {
  const [items, setItems] = useState<MasterItem[]>([]); const [search, setSearch] = useState(""); const [category, setCategory] = useState<ChecklistCategory | "all">("all"); const [editor, setEditor] = useState<MasterItem>(); const [error, setError] = useState("");
  const refresh = async () => { try { setItems(await listMasterItems()); } catch { setError("Couldn’t load your inventory."); } };
  useEffect(() => { let alive = true; void listMasterItems().then((next) => { if (alive) setItems(next); }).catch(() => { if (alive) setError("Couldn’t load your inventory."); }); return () => { alive = false; }; }, []);
  const visible = useMemo(() => findMasterItems(items, search, category), [items, search, category]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const name = String(values.get("name") ?? "").trim(); if (!name) return; const rule = quantityRule(values); const next: MasterItem = { id: editor?.id ?? createId(), name, category: String(values.get("category")) as ChecklistCategory, section: String(values.get("section") ?? "General").trim() || "General", defaultQuantity: Math.max(0, Number(values.get("quantity")) || 0), unit: String(values.get("unit") ?? "item").trim() || "item", tripStyles: editor?.tripStyles ?? ["car", "light-backpacking", "custom"], tags: split(values.get("tags")), aliases: split(values.get("aliases")), archived: false, source: editor?.source ?? "user", ...(rule === undefined ? {} : { quantityRule: rule }) }; await saveMasterItem(next); await refresh(); setEditor(undefined); }
  async function archive(item: MasterItem) { await archiveMasterItem(item.id); await refresh(); }
  return <main className="app-shell"><header className="trip-header"><button className="text-button" type="button" onClick={onBack}>← All trips</button><p className="eyebrow">MASTER INVENTORY</p><h1>Everything you may bring.</h1><p className="trip-destination">Organize reusable items once, then generate a clean trip checklist.</p></header><section className="inventory-card"><div className="section-heading"><div><p className="eyebrow">{items.length} ACTIVE ITEMS</p><h2>Inventory</h2></div><button className="primary-action" type="button" onClick={() => setEditor(newItem())}>+ Add item</button></div><div className="toolbar"><input aria-label="Search inventory" placeholder="Search names, aliases, tags" value={search} onChange={(event) => setSearch(event.target.value)} /><select aria-label="Filter inventory category" value={category} onChange={(event) => setCategory(event.target.value as ChecklistCategory | "all")}><option value="all">All categories</option>{Object.entries(categories).map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select></div>{error ? <p className="error-message">{error}</p> : <ul className="item-list">{visible.map((item) => <li className="inventory-item" key={item.id}><div><strong>{item.name}</strong><small>{categories[item.category]} · {item.section} · {quantityLabel(item)}</small>{item.aliases?.length ? <small>Also known as: {item.aliases.join(", ")}</small> : null}</div><button className="promote" type="button" onClick={() => setEditor(item)}>Edit</button><button className="promote danger" type="button" onClick={() => void archive(item)}>Archive</button></li>)}</ul>}</section>{editor && <Editor item={editor} onClose={() => setEditor(undefined)} onSubmit={submit} />}</main>;
}

function Editor({ item, onClose, onSubmit }: { item: MasterItem; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { const rule = item.quantityRule; return <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true" aria-label="Edit inventory item"><div className="dialog-heading"><h2>{item.name ? "Edit item" : "Add inventory item"}</h2><button className="text-button" type="button" aria-label="Close dialog" onClick={onClose}>×</button></div><form onSubmit={onSubmit}><label>Name<input name="name" defaultValue={item.name} autoFocus required /></label><div className="field-row"><label>Category<select name="category" defaultValue={item.category}>{Object.entries(categories).map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select></label><label>Section<input name="section" defaultValue={item.section} required /></label></div><div className="field-row"><label>Default quantity<input name="quantity" type="number" min="0" defaultValue={item.defaultQuantity} /></label><label>Unit<input name="unit" defaultValue={item.unit} /></label></div><fieldset className="rule-editor"><legend>Generated quantity</legend><p>Rules calculate the first trip quantity. A trip item can always be changed later.</p><div className="field-row"><label>Rule<select name="ruleKind" defaultValue={rule?.kind ?? "none"}><option value="none">Fixed default</option><option value="fixed">Fixed amount</option><option value="per-person">Per person</option><option value="per-day">Per night</option><option value="per-person-per-day">Per person, per night</option></select></label><label>Amount<input name="ruleAmount" type="number" min="0" defaultValue={rule?.amount ?? item.defaultQuantity} /></label></div></fieldset><label>Aliases <small>Comma-separated; included in search.</small><input name="aliases" defaultValue={item.aliases?.join(", ")} /></label><label>Tags <small>Comma-separated.</small><input name="tags" defaultValue={item.tags.join(", ")} /></label><button className="primary-action" type="submit">Save item</button></form></section></div>; }

function newItem(): MasterItem { return { id: createId(), name: "", category: "extras", section: "Custom items", defaultQuantity: 1, unit: "item", tripStyles: ["car", "light-backpacking", "custom"], tags: [], aliases: [], archived: false, source: "user" }; }
function split(value: FormDataEntryValue | null): string[] { return String(value ?? "").split(",").map((item) => item.trim()).filter(Boolean); }
function quantityRule(values: FormData): QuantityRule | undefined { const kind = String(values.get("ruleKind")); const amount = Math.max(0, Number(values.get("ruleAmount")) || 0); return kind === "none" ? undefined : { kind: kind as QuantityRule["kind"], amount }; }
function quantityLabel(item: MasterItem): string { if (!item.quantityRule) return `${item.defaultQuantity} ${item.unit}`; const labels: Record<QuantityRule["kind"], string> = { fixed: "fixed", "per-person": "per person", "per-day": "per night", "per-person-per-day": "per person/night" }; return `${item.quantityRule.amount} ${item.unit} ${labels[item.quantityRule.kind]}`; }
