import type { RouteTrack, Waypoint } from "../domain/models";
import { distanceAndBearing } from "./waypointService";

export function parseGpx(text: string, tripId: string): { waypoints: Waypoint[]; routes: RouteTrack[] } {
  const document = new DOMParser().parseFromString(text, "application/xml");
  if (document.querySelector("parsererror") || document.documentElement.localName !== "gpx") throw new Error("This is not valid GPX.");
  const now = new Date().toISOString();
  const points = (nodes: NodeListOf<Element>) => [...nodes].flatMap((node) => { const latitude = Number(node.getAttribute("lat")), longitude = Number(node.getAttribute("lon")); if (!Number.isFinite(latitude) || !Number.isFinite(longitude)) return []; const elevation = Number(node.querySelector(":scope > ele")?.textContent); return [{ latitude, longitude, ...(Number.isFinite(elevation) ? { elevation } : {}) }]; });
  const waypoints = [...document.querySelectorAll("wpt")].flatMap((node, index) => { const [point] = points([node] as unknown as NodeListOf<Element>); if (!point) return []; return [{ id: `gpx-waypoint-${crypto.randomUUID()}`, tripId, type: "custom" as const, name: node.querySelector(":scope > name")?.textContent?.trim() || `Imported waypoint ${index + 1}`, latitude: point.latitude, longitude: point.longitude, ...(point.elevation === undefined ? {} : { notes: `Elevation: ${point.elevation} m` }), createdAt: now, updatedAt: now }]; });
  const routes = [...document.querySelectorAll("rte, trk")].flatMap((node, index) => { const routePoints = points(node.querySelectorAll(node.localName === "trk" ? "trkpt" : "rtept")); if (routePoints.length < 2) return []; const kind = node.localName === "trk" ? "track" as const : "route" as const; return [{ id: `gpx-${kind}-${crypto.randomUUID()}`, tripId, kind, name: node.querySelector(":scope > name")?.textContent?.trim() || `Imported ${kind} ${index + 1}`, points: routePoints, distanceMeters: distance(routePoints), createdAt: now, updatedAt: now }]; });
  if (!waypoints.length && !routes.length) throw new Error("The GPX file does not contain supported waypoints, routes, or tracks.");
  return { waypoints, routes };
}
export function exportGpx(waypoints: Waypoint[], routes: RouteTrack[]): string { const point = (tag: string, entry: { latitude: number; longitude: number; elevation?: number }, name?: string) => `<${tag} lat="${entry.latitude}" lon="${entry.longitude}">${name ? `<name>${escape(name)}</name>` : ""}${entry.elevation === undefined ? "" : `<ele>${entry.elevation}</ele>`}</${tag}>`; return `<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Camping Checklist" xmlns="http://www.topografix.com/GPX/1/1">${waypoints.map((waypoint) => point("wpt", waypoint, waypoint.name)).join("")}${routes.map((route) => route.kind === "track" ? `<trk><name>${escape(route.name)}</name><trkseg>${route.points.map((entry) => point("trkpt", entry)).join("")}</trkseg></trk>` : `<rte><name>${escape(route.name)}</name>${route.points.map((entry) => point("rtept", entry)).join("")}</rte>`).join("")}</gpx>`; }
function distance(points: Array<{ latitude: number; longitude: number }>): number { return points.slice(1).reduce((total, point, index) => total + distanceAndBearing(points[index]!, point).meters, 0); }
function escape(value: string): string { return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;"); }
